/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardExplorerRouteImport } from './routes/_dashboard/explorer'
import { Route as DashboardCleanupRouteImport } from './routes/_dashboard/cleanup'
import { Route as AuthProviderCallbackRouteImport } from './routes/auth/$provider/callback'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExplorerRoute = DashboardExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCleanupRoute = DashboardCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthProviderCallbackRoute = AuthProviderCallbackRouteImport.update({
  id: '/auth/$provider/callback',
  path: '/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cleanup': typeof DashboardCleanupRoute
  '/explorer': typeof DashboardExplorerRoute
  '/settings': typeof DashboardSettingsRoute
  '/': typeof DashboardIndexRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cleanup': typeof DashboardCleanupRoute
  '/explorer': typeof DashboardExplorerRoute
  '/settings': typeof DashboardSettingsRoute
  '/': typeof DashboardIndexRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_dashboard/cleanup': typeof DashboardCleanupRoute
  '/_dashboard/explorer': typeof DashboardExplorerRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/setup'
    | '/cleanup'
    | '/explorer'
    | '/settings'
    | '/'
    | '/auth/$provider/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/cleanup'
    | '/explorer'
    | '/settings'
    | '/'
    | '/auth/$provider/callback'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/setup'
    | '/_dashboard/cleanup'
    | '/_dashboard/explorer'
    | '/_dashboard/settings'
    | '/_dashboard/'
    | '/auth/$provider/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  AuthProviderCallbackRoute: typeof AuthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/explorer': {
      id: '/_dashboard/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof DashboardExplorerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cleanup': {
      id: '/_dashboard/cleanup'
      path: '/cleanup'
      fullPath: '/cleanup'
      preLoaderRoute: typeof DashboardCleanupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/$provider/callback': {
      id: '/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof AuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCleanupRoute: typeof DashboardCleanupRoute
  DashboardExplorerRoute: typeof DashboardExplorerRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCleanupRoute: DashboardCleanupRoute,
  DashboardExplorerRoute: DashboardExplorerRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  AuthProviderCallbackRoute: AuthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
