/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardSubscriptionsRouteImport } from './routes/_dashboard/subscriptions'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardFiltersRouteImport } from './routes/_dashboard/filters'
import { Route as DashboardExplorerRouteImport } from './routes/_dashboard/explorer'
import { Route as DashboardFiltersIndexRouteImport } from './routes/_dashboard/filters/index'
import { Route as AuthProviderCallbackRouteImport } from './routes/auth/$provider/callback'
import { Route as DashboardFiltersNewRouteImport } from './routes/_dashboard/filters/new'
import { Route as DashboardFiltersFilterIdRouteImport } from './routes/_dashboard/filters/$filterId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFiltersRoute = DashboardFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExplorerRoute = DashboardExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFiltersIndexRoute = DashboardFiltersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFiltersRoute,
} as any)
const AuthProviderCallbackRoute = AuthProviderCallbackRouteImport.update({
  id: '/auth/$provider/callback',
  path: '/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFiltersNewRoute = DashboardFiltersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardFiltersRoute,
} as any)
const DashboardFiltersFilterIdRoute = DashboardFiltersFilterIdRouteImport.update({
  id: '/$filterId',
  path: '/$filterId',
  getParentRoute: () => DashboardFiltersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/explorer': typeof DashboardExplorerRoute
  '/filters': typeof DashboardFiltersRouteWithChildren
  '/settings': typeof DashboardSettingsRoute
  '/subscriptions': typeof DashboardSubscriptionsRoute
  '/': typeof DashboardIndexRoute
  '/filters/$filterId': typeof DashboardFiltersFilterIdRoute
  '/filters/new': typeof DashboardFiltersNewRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/filters/': typeof DashboardFiltersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/explorer': typeof DashboardExplorerRoute
  '/settings': typeof DashboardSettingsRoute
  '/subscriptions': typeof DashboardSubscriptionsRoute
  '/': typeof DashboardIndexRoute
  '/filters/$filterId': typeof DashboardFiltersFilterIdRoute
  '/filters/new': typeof DashboardFiltersNewRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/filters': typeof DashboardFiltersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_dashboard/explorer': typeof DashboardExplorerRoute
  '/_dashboard/filters': typeof DashboardFiltersRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/filters/$filterId': typeof DashboardFiltersFilterIdRoute
  '/_dashboard/filters/new': typeof DashboardFiltersNewRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/_dashboard/filters/': typeof DashboardFiltersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/setup'
    | '/explorer'
    | '/filters'
    | '/settings'
    | '/subscriptions'
    | '/'
    | '/filters/$filterId'
    | '/filters/new'
    | '/auth/$provider/callback'
    | '/filters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/explorer'
    | '/settings'
    | '/subscriptions'
    | '/'
    | '/filters/$filterId'
    | '/filters/new'
    | '/auth/$provider/callback'
    | '/filters'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/setup'
    | '/_dashboard/explorer'
    | '/_dashboard/filters'
    | '/_dashboard/settings'
    | '/_dashboard/subscriptions'
    | '/_dashboard/'
    | '/_dashboard/filters/$filterId'
    | '/_dashboard/filters/new'
    | '/auth/$provider/callback'
    | '/_dashboard/filters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  AuthProviderCallbackRoute: typeof AuthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/subscriptions': {
      id: '/_dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/filters': {
      id: '/_dashboard/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof DashboardFiltersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/explorer': {
      id: '/_dashboard/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof DashboardExplorerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/filters/': {
      id: '/_dashboard/filters/'
      path: '/'
      fullPath: '/filters/'
      preLoaderRoute: typeof DashboardFiltersIndexRouteImport
      parentRoute: typeof DashboardFiltersRoute
    }
    '/auth/$provider/callback': {
      id: '/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof AuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/filters/new': {
      id: '/_dashboard/filters/new'
      path: '/new'
      fullPath: '/filters/new'
      preLoaderRoute: typeof DashboardFiltersNewRouteImport
      parentRoute: typeof DashboardFiltersRoute
    }
    '/_dashboard/filters/$filterId': {
      id: '/_dashboard/filters/$filterId'
      path: '/$filterId'
      fullPath: '/filters/$filterId'
      preLoaderRoute: typeof DashboardFiltersFilterIdRouteImport
      parentRoute: typeof DashboardFiltersRoute
    }
  }
}

interface DashboardFiltersRouteChildren {
  DashboardFiltersFilterIdRoute: typeof DashboardFiltersFilterIdRoute
  DashboardFiltersNewRoute: typeof DashboardFiltersNewRoute
  DashboardFiltersIndexRoute: typeof DashboardFiltersIndexRoute
}

const DashboardFiltersRouteChildren: DashboardFiltersRouteChildren = {
  DashboardFiltersFilterIdRoute: DashboardFiltersFilterIdRoute,
  DashboardFiltersNewRoute: DashboardFiltersNewRoute,
  DashboardFiltersIndexRoute: DashboardFiltersIndexRoute,
}

const DashboardFiltersRouteWithChildren = DashboardFiltersRoute._addFileChildren(
  DashboardFiltersRouteChildren
)

interface DashboardRouteChildren {
  DashboardExplorerRoute: typeof DashboardExplorerRoute
  DashboardFiltersRoute: typeof DashboardFiltersRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardExplorerRoute: DashboardExplorerRoute,
  DashboardFiltersRoute: DashboardFiltersRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(DashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  AuthProviderCallbackRoute: AuthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
